version: '3.7'

services:
  mongo:
    image: mongo:latest
    restart: always
    env_file:
      - .env.develop
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./data/db/mongo
      - ./mongod.conf:/etc/mongod.conf
    ports:
      - "27017:27017"

  redis:
    image: redis
    restart: always
    volumes:
      - /data/db/redis
    ports:
      - "6379:6379"
