export const PROJECT_INSERT = 'PROJECT_INSERT';
export const PROJECT_EDIT = 'PROJECT_EDIT';
export const PROJECT_DELETE = 'PROJECT_DELETE';
export const PROJECT_FETCH = 'PROJECT_FETCH';
export const PROJECT_SELECT = 'PROJECT_SELECT';
